---
- name: Deploying fastapi application with local postgre.
  hosts: app-deployment_servers
  become: yes
  vars:
    app_dir: /var/www/fastapi_app
    venv_dir: "{{ app_dir }}/venv"
    app_user: ubuntu
    app_port: 8000
    db_name: mycruddb
    db_user: postgres
    db_password: "Terraform@nsib1e33$$$10"
    database_url: "postgresql://{{ db_user }}:{{ db_password }}@localhost:5432/{{ db_name }}"

  tasks:
    - name: update apt cache (for Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Installing common system dependencies
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
          - python3-venv
          - build-essential
          - libpq-dev
        state: present

    - name: Installing postgresql server
      ansible.builtin.package:
        name:
          - postgresql
          - postgresql-contrib
        state: present

    - name: Ensure postgre service is running and enabled
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: yes

    - name: password for postgres user
      ansible.builtin.shell:
        cmd: "echo \"ALTER USER {{ db_user }} WITH PASSWORD '{{ db_password }}';\" | sudo -u {{ db_user }} psql"

    - name: creating postgre database for the application
      ansible.builtin.shell:
        cmd: "sudo -u {{ db_user }} psql -tc \"SELECT 1 FROM pg_database WHERE datname='{{ db_name }}'\" | grep -q 1 || sudo -u {{ db_user }} createdb -O {{ db_user }} {{ db_name }}"

    - name: pause to allow postgre to initialize
      ansible.builtin.pause:
        seconds: 5
        prompt: "waiting for postgresql to be ready..."

    - name: create application base directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: copy application files into a directory on the server
      ansible.builtin.copy:
        src: ./app 
        dest: "{{ app_dir }}/" 
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: ensuring __init__.py exists in the app package directory, if not already present
      ansible.builtin.file:
        path: "{{ app_dir }}/app/__init__.py"
        state: touch
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0644'

    - name: creation of python virtual environment
      ansible.builtin.command: "python3 -m venv {{ venv_dir }}"
      args:
        creates: "{{ venv_dir }}/bin/python"

    - name: installation of python dependencies from requirements file.
      ansible.builtin.pip:
        requirements: "{{ app_dir }}/app/requirements.txt"
        virtualenv: "{{ venv_dir }}"
        virtualenv_command: python3 -m venv

    - name: ensuring gunicorn and uvicorn are installed in venv
      ansible.builtin.pip:
        name:
          - gunicorn
          - uvicorn
        virtualenv: "{{ venv_dir }}"
        virtualenv_command: python3 -m venv
        state: present

    - name: run sqlalchemy migrations (create tables)
      ansible.builtin.shell:
        cmd: "{{ venv_dir }}/bin/python -c \"from app.database import Base, engine; Base.metadata.create_all(bind=engine)\""
        chdir: "{{ app_dir }}"
      environment:
        DATABASE_URL: "{{ database_url }}"

    - name: creating systemd service file for fastapi app
      ansible.builtin.template:
        src: fastapi_app.service.j2
        dest: /etc/systemd/system/fastapi_app.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload systemd
        - Start FastAPI app

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart FastAPI app
      ansible.builtin.service:
        name: fastapi_app
        state: restarted

    - name: Start FastAPI app
      ansible.builtin.service:
        name: fastapi_app
        state: started
        enabled: yes

    - name: Restart PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted
